config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
      controllers: {
          omniauth_callbacks: 'omniauth_callbacks'
      },
      skip: [:sessions]

  # Manually manage sign out path due to the lack of database authenticatable
  devise_scope :user do
	  post   '/users/auth/2fa' => 'omniauth_callbacks#authenticate_with_two_factor' # Handle 2FA callbacks
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :activity, only: [:index]

  resources :airports

  resources :certifications

  resources :events do
    get 'signup' => 'events/signups#new'

    resources :signups, except: [:new], controller: 'events/signups'
    resources :pilots, only: [:create, :destroy], controller: 'events/pilots'
    resources :positions, except: [:create, :destroy, :new, :show], controller: 'events/positions'
  end

  resources :feedback, except: [:edit, :show]
  resources :groups, except: [:show]
  resources :positions

  resource :profile, only: [:show, :update] do
    resource :gpg_key, only: [:create, :destroy, :show], controller: 'profiles/gpg_key'
	  resource :two_factor_auth, only: [:create, :destroy, :show], controller: 'profiles/two_factor_auths' do
		  resources :u2f, only: [:create, :destroy], controller: 'profiles/two_factor_auths/u2f'
	  end
  end

  resources :roster, as: :users do
	  get    'user_info'   => 'roster#user_info'
	  delete 'disable_2fa' => 'roster#disable_2fa'
	  resources :endorsements, only: [:create, :edit, :new, :update, :destroy]
  end
end

app/models/group.rb
class Group < ApplicationRecord
  extend FriendlyId
  friendly_id :name

  BUILT_IN_GROUPS = [ 'Air Traffic Manager',
                      'Deputy Air Traffic Manager',
                      'Training Administrator',
                      'Facility Engineer',
                      'Events Coordinator',
                      'Webmaster',
                      'Controller',
                      'Guest',
                      'Public' ]

  has_many :assignments
  has_many :permissions, through: :assignments
  has_many :users

  before_destroy :ensure_not_builtin
  before_destroy :ensure_no_members

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :min_controlling_hours,
            presence: true,
            numericality: { is_greater_than_or_equal_to: 0 }

  validate :builtin_unchanged

  # Titleize the group name
  #
  def name=(name)
    name.nil? ? super(name) : super(name.titleize)
  end

  private

  # Ensures the built in group names have not changed
  def builtin_unchanged
    if name_changed?
      if BUILT_IN_GROUPS.include? name_was
        self.errors[:name] << 'Built in group names cannot be changed'
      end
    end # if name.changed?
  end

  # Ensures the group cannot be deleted if members still exist
  def ensure_no_members
    unless users.empty?
      self.errors[:name] << 'Members still exist for this group'
      throw :abort
    end
  end

  # Ensures the built in groups cannot be deleted
  def ensure_not_builtin
    if BUILT_IN_GROUPS.include?(name)
      self.errors[:name] << 'Built in groups cannot be deleted'
      throw :abort
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @groups = Group.all.order(:name)
    authorize @groups
  end

  def create
    authorize Group, :create?
    @group = Group.new

    if @group.update_attributes(permitted_attributes(@group))
      redirect_to groups_path, success: 'Group created'
    else
      flash.now[:alert] = 'Unable to create group'
      render :new
    end
  end

  def destroy
    authorize Group, :destroy?
    @group = policy_scope(Group).friendly.find(params[:id])

    if @group.destroy
      redirect_to groups_path, success: 'Group has been deleted'
    else
      flash[:alert] = 'Unable to delete group'
      render :edit
    end
  end

  def edit
    @group = policy_scope(Group).friendly.find(params[:id])
    authorize @group
  end

  def new
    @group = Group.new
    authorize @group
  end

  def update
    authorize Group, :update?
    @group = policy_scope(Group).friendly.find(params[:id])

    if @group.update_attributes(permitted_attributes(@group))
      redirect_to groups_path, success: 'Group has been updated'
    else
      flash.now[:alert] = 'Unable to update group'
      render :edit
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="container">
  <%= form_for @group do |f| %>

      <div class="form-group row">
        <%= f.label :name, 'Group Name', class: 'col-sm-3 col-form-label' %>
        <div class="col-sm-9">
          <% @group.errors[:name].present? ? name_invalid = 'is-invalid' : name_invalid = nil %>
          <%= f.text_field :name, class: "form-control #{name_invalid}", required: true %>
          <% unless name_invalid.nil? %>
            <div class="invalid-feedback">
              <%= @group.errors[:name].join(', ').capitalize %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :staff, 'Staff Position', class: 'col-sm-3 col-form-label' %>
        <div class="col-sm-9">
          <% @group.errors[:staff].present? ? staff_invalid = 'is-invalid' : staff_invalid = nil %>
          <%= f.select :staff, [['Yes', true], ['No', false]], {}, class: "form-control #{staff_invalid}" %>
          <small id="minHoursHelp" class="form-text text-muted">
            Identifies this group as a staff position
          </small>
          <% unless staff_invalid.nil? %>
            <div class="invalid-feedback">
              <%= @group.errors[:staff].join(', ').capitalize %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :atc, 'Controllers', class: 'col-sm-3 col-form-label' %>
        <div class="col-sm-9">
          <% @group.errors[:atc].present? ? atc_invalid = 'is-invalid' : atc_invalid = nil %>
          <%= f.select :atc, [['Yes', true], ['No', false]], {}, class: "form-control #{atc_invalid}" %>
          <small id="minHoursHelp" class="form-text text-muted">
            Determines whether this group has controlling privileges
          </small>
          <% unless atc_invalid.nil? %>
            <div class="invalid-feedback">
              <%= @group.errors[:atc].join(', ').capitalize %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :visiting, 'Visiting Controllers', class: 'col-sm-3 col-form-label' %>
        <div class="col-sm-9">
          <% @group.errors[:visiting].present? ? visiting_invalid = 'is-invalid' : visiting_invalid = nil %>
          <%= f.select :visiting, [['Yes', true], ['No', false]], {}, class: "form-control #{visiting_invalid}" %>
          <small id="minHoursHelp" class="form-text text-muted">
            Marks members of this group as visiting controllers
          </small>
          <% unless visiting_invalid.nil? %>
            <div class="invalid-feedback">
              <%= @group.errors[:visiting].join(', ').capitalize %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :min_controlling_hours, 'Minimum Hours', class: 'col-sm-3 col-form-label' %>
        <div class="col-sm-9">
          <% @group.errors[:min_controlling_hours].present? ? activity_invalid = 'is-invalid' : activity_invalid = nil %>
          <%= f.text_field :min_controlling_hours, class: "form-control #{activity_invalid}" %>
          <small id="minHoursHelp" class="form-text text-muted">
            The minimum number of hours this group must control to remain active on the roster
          </small>
          <% unless activity_invalid.nil? %>
            <div class="invalid-feedback">
              <%= @group.errors[:min_controlling_hours].join(', ').capitalize %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :two_factor_required, 'Two-factor authentication', class: 'col-sm-3 col-form-label' %>
        <div class="col-sm-9">
          <% @group.errors[:two_factor_required].present? ? two_fa_invalid = 'is-invalid' : two_fa_invalid = nil %>
          <div class="form-check">
            <label class="form-check-label">
              <%= f.check_box :two_factor_required, class: "form-check-input #{two_fa_invalid}" %>
              Require all users in this group to setup two-factor authentication
            </label>
          </div>
          <% unless two_fa_invalid.nil? %>
            <div class="invalid-feedback">
              <%= @group.errors[:two_factor_required].join(', ').capitalize %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :permissions, 'Permissions', class: 'col-sm-3 col-form-label' %>
        <div class="col-sm-9">
          <% @group.errors[:permissions].present? ? permissions_invalid = 'is-invalid' : permissions_invalid = nil %>
          <% options = options_from_collection_for_select(Permission.all.order(:name), 'id', 'name', @group.permissions.pluck('id')) %>
          <%= f.select :permission_ids, options, {}, multiple: true, size: 10, class: "form-control #{permissions_invalid}" %>
          <% unless permissions_invalid.nil? %>
              <div class="invalid-feedback">
                <%= @group.errors[:permissions].join(', ').capitalize %>
              </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-12 text-center">
          <%= f.submit 'Save Group', class: 'btn btn-primary' %>
          <%= link_to 'Cancel', groups_path, class: 'btn btn-outline-info' %>
        </div>
      </div>
  <% end %>
</div>

app/views/groups/_group.html.erb
<tr>
  <% if policy(Group).update? -%>
    <td class="text-center">
      <%= link_to edit_group_path(group),
                  class: 'badge badge-secondary',
                  'data-toggle': :tooltip,
                  'data-placement': :bottom,
                  title: 'Edit' do %>
        <%= fa_icon 'pencil' %>
      <% end %>
    </td>
  <% end -%>
  <td>
    <small><%= group.name %></small>
  </td>
  <td class="text-center">
    <small>
      <%= group.atc? ? fa_icon(:check) : nil %>
    </small>
  </td>
  <td class="text-center">
    <small>
      <%= group.visiting? ? fa_icon(:check) : nil %>
    </small>
  </td>
  <td class="text-center">
    <small>
      <%= group.staff? ? fa_icon(:check) : nil %>
    </small>
  </td>
  <td class="text-center">
    <small>
      <%= group.two_factor_required? ? fa_icon(:check) : nil %>
    </small>
  </td>
  <td class="text-center">
    <small><%= group.users.count %></small>
  </td>
</tr>

app/views/groups/edit.html.erb
<% content_for(:title, "Edit Group: #{@group.name}") %>

<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header bg-dark text-light">
        <div class="row">
          <div class="col-auto mr-auto pt-1">
            Edit <%= @group.name %>
          </div>
          <% if policy(@group).destroy? -%>
            <div class="col-auto">
              <%= link_to '#', class: 'btn btn-sm btn-outline-danger', title: 'Delete Group', data: {toggle: :modal, target: '#groupDeleteModal'} do %>
                <%= fa_icon('trash') %> Delete
              <% end %>
            </div>
          <% end -%>
        </div>
      </div>

      <div class="card-body pl-0 pr-0">
        <%= render 'form' %>
      </div>

    </div>
  </div>
</div>

<!-- Deletion Modal -->
<div class="modal fade" id="groupDeleteModal" tabindex="-1" role="dialog" aria-labelledby="groupDeleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="positionDeleteModalLabel">
          <%= fa_icon 'exclamation-triangle', class: 'text-danger' %> Delete Group
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete <%= @group.name %>?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= link_to 'Delete', group_path(@group), method: :delete, class: 'btn btn-danger', data: { dismiss: :modal } %>
      </div>
    </div>
  </div>
</div>
<!-- End Deletion Modal -->

app/views/groups/index.html.erb
<% content_for(:title, 'Group Management') %>

<div class="row">
  <div class="col-lg-12">
    <div class="card border-0">
      <div class="card-header bg-dark text-light">
        <div class="row">
          <div class="col-auto mr-auto pt-1">
            Groups
          </div>
          <% if policy(Group).create? -%>
              <div class="col-auto">
                <%= link_to new_group_path, class: 'event-title-btn', 'data-toggle': :tooltip, 'data-placement': :bottom, title: 'Add Group' do %>
                  <%= fa_icon('plus-square') %>
                <% end %>
              </div>
          <% end -%>
        </div>
      </div>

      <div class="card-body pb-0 pl-0 pr-0 pt-0">
        <table class="table table-sm table-bordered table-responsive mb-0">
          <tbody>
          <tr class="bg-light">
            <% if policy(Group).update? -%>
                <th></th>
            <% end -%>
            <th class="text-center">
              <small>Name</small>
            </th>
            <th class="text-center">
              <small>Controllers</small>
            </th>
            <th class="text-center">
              <small>Visiting Controllers</small>
            </th>
            <th class="text-center">
              <small>Staff</small>
            </th>
            <th class="text-center">
              <small>2FA Required</small>
            </th>
            <th class="text-center">
              <small>Users</small>
            </th>
          </tr>
          <% if @groups.empty? %>
              <tr>
                <td colspan="6" class="text-center">
                  <small><i>No information available</i></small>
                </td>
              </tr>
          <% end %>

          <% @groups.each do |g| -%>
            <%= render 'group', group: g %>
          <% end -%>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

app/views/groups/new.html.erb
<% content_for(:title, 'Group Management - New Group') %>

<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header bg-dark text-light">
        New Group
      </div>

      <div class="card-body pl-0 pr-0">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>