config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
      controllers: {
          omniauth_callbacks: 'omniauth_callbacks'
      },
      skip: [:sessions]

  # Manually manage sign out path due to the lack of database authenticatable
  devise_scope :user do
	  post   '/users/auth/2fa' => 'omniauth_callbacks#authenticate_with_two_factor' # Handle 2FA callbacks
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :activity, only: [:index]

  resources :airports

  resources :certifications

  resources :events do
    get 'signup' => 'events/signups#new'

    resources :signups, except: [:new], controller: 'events/signups'
    resources :pilots, only: [:create, :destroy], controller: 'events/pilots'
    resources :positions, except: [:create, :destroy, :new, :show], controller: 'events/positions'
  end

  resources :feedback, except: [:edit, :show]
  resources :groups, except: [:show]
  resources :positions

  resource :profile, only: [:show, :update] do
    resource :gpg_key, only: [:create, :destroy, :show], controller: 'profiles/gpg_key'
	  resource :two_factor_auth, only: [:create, :destroy, :show], controller: 'profiles/two_factor_auths' do
		  resources :u2f, only: [:create, :destroy], controller: 'profiles/two_factor_auths/u2f'
	  end
  end

  resources :roster, as: :users do
	  get    'user_info'   => 'roster#user_info'
	  delete 'disable_2fa' => 'roster#disable_2fa'
	  resources :endorsements, only: [:create, :edit, :new, :update, :destroy]
  end
end

app/models/certification.rb
class Certification < ApplicationRecord

  has_many :endorsements, dependent: :destroy
  has_many :positions
  has_many :users, through: :endorsements

  validates :name, presence: true, allow_blank: false, uniqueness: {case_sensitive: false, scope: :major}
  validates :short_name, presence: true, allow_blank: false
  # validates :positions, length: { minimum: 1, message: 'most contain at least one' }
  # validates :show_on_roster, presence: true
  validate :same_kind

  # Titleize the name
  #
  def name=(name)
    name.nil? ? super(name) : super(name.titleize)
  end

  # Ensure the short name is capitalized
  #
  def short_name=(name)
    name.nil? ? super(name) : super(name.upcase)
  end

  private

  # Validates that a certification contains only major or minor
  # positions but not a combination of both
  def same_kind
    unless positions.empty?
      if positions.collect(&:major).uniq != [major?]
        errors[:positions] << 'must match major certification status'
      end
    end
  end

end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController

	before_action :authenticate_user!
	after_action :verify_authorized

	def index
		@certifications = Certification.all
		authorize @certifications
	end

	def create
		authorize Certification, :create?
		@certification = Certification.new

		if @certification.update_attributes(permitted_attributes(@certification))
			redirect_to certifications_path, success: 'Certification has been saved'
		else
			flash.now[:alert] = 'Unable to create certification'
			render :new
		end
	end

	def destroy
		authorize Certification, :destroy?
		@certification = policy_scope(Certification).find(params[:id])

		if @certification.destroy
			redirect_to certifications_path, success: 'Certification has been deleted'
		else
			redirect_to certifications_path(@certification), alert: 'Unable to delete position'
		end
	end

	def edit
		@certification = policy_scope(Certification).find(params[:id])
		authorize @certification
	end

	def new
		@certification = Certification.new
		authorize @certification
	end

	def show
		@certification = policy_scope(Certification).find(params[:id])
		authorize @certification
	end

	def update
		authorize Certification, :update?
		@certification = policy_scope(Certification).find(params[:id])

		if @certification.update_attributes(permitted_attributes(@certification))
			flash[:success] = "#{@certification.name} certification has been updated"
			redirect_to certifications_path
		else
			flash.now[:alert] = 'Unable to update certification'
			render :edit
		end
	end

end

app/helpers/certifications_helper.rb
module CertificationsHelper
end

app/views/certifications/_form.html.erb
<div class="container">
  <%= form_for @certification do |f| %>

      <div class="form-group row">
        <%= f.label :name, 'Certification Name', class: 'col-sm-3 col-form-label' %>
        <div class="col-sm-9">
          <% @certification.errors[:name].present? ? name_invalid = 'is-invalid' : name_invalid = nil %>
          <%= f.text_field :name, class: "form-control #{name_invalid}", placeholder: 'Example: Houston Center Major', required: true %>
          <% unless name_invalid.nil? %>
            <div class="invalid-feedback">
              <%= @certification.errors[:name].join(', ').capitalize %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :short_name, 'Short Name', class: 'col-sm-3 col-form-label' %>
        <div class="col-sm-9">
          <% @certification.errors[:short_name].present? ? short_name_invalid = 'is-invalid' : short_name_invalid = nil %>
          <%= f.text_field :short_name, class: "form-control #{short_name_invalid}", maxlength: 5, placeholder: 'Example: CTR', required: true %>
          <% unless short_name_invalid.nil? %>
            <div class="invalid-feedback">
              <%= @certification.errors[:short_name].join(', ').capitalize %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-3 col-form-label">Roster Display</div>
        <div class="col-sm-9 form-check form-check-inline">
          <%= f.check_box :show_on_roster, class: 'form-check-label' %>
          <%= f.label 'Show certification status on roster', class: 'col-form-label' %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-3 col-form-label">Major</div>
        <div class="col-sm-9 form-check form-check-inline">
          <%= f.check_box :major, class: 'form-check-label' %>
          <%= f.label 'This is a major position certification', class: 'col-form-label' %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :positions, 'Positions', class: 'col-sm-3 col-form-label' %>
        <div class="col-sm-9">
          <% @certification.errors[:positions].present? ? positions_invalid = 'is-invalid' : positions_invalid = nil %>
          <% positions = Position.all.order(:callsign).collect{|p| ["#{p.to_s} #{p.major? ? '  [Major Position]' : ''}", p.id]} %>
          <%= f.select :position_ids, positions, {}, multiple: true, class: "form-control #{positions_invalid}" %>
          <% unless positions_invalid.nil? %>
            <div class="invalid-feedback">
              <%= @certification.errors[:positions].join(', ').capitalize %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-12 text-center">
          <%= f.submit 'Save Certification', class: 'btn btn-primary' %>
          <%= link_to 'Cancel', certifications_path, class: 'btn btn-outline-info' %>
        </div>
      </div>
  <% end %>
</div>

app/views/certifications/edit.html.erb
<% content_for(:title, "Certifications - #{@certification.name}") %>

<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header bg-dark text-light">
        <div class="row">
          <div class="col-auto mr-auto pt-1">
            Edit Certification: <%= @certification.name %>
          </div>
          <% if policy(@certification).destroy? -%>
              <div class="col-auto">
                <%= link_to '#', class: 'btn btn-sm btn-outline-danger', title: 'Delete Certification', data: {toggle: :modal, target: '#certificationDeleteModal'} do %>
                    <%= fa_icon('trash') %> Delete
                <% end %>
              </div>
          <% end -%>
        </div>
      </div>

      <div class="card-body pl-0 pr-0">
        <%= render 'form' %>
      </div>

    </div>
  </div>
</div>

<!-- Deletion Modal -->
<div class="modal fade" id="certificationDeleteModal" tabindex="-1" role="dialog" aria-labelledby="certificationDeleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="certificationDeleteModalLabel">
          <%= fa_icon 'exclamation-triangle', class: 'text-danger' %> Delete Certification
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>
          Are you sure you want to delete the <b><%= @certification.name %></b> certification?
        </p>
        <% unless @certification.endorsements.empty? -%>
          <p>
            <b>Deleting this certification will remove <%= @certification.endorsements.count %> endorsements!</b>
          </p>
        <% end -%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= link_to 'Delete', certification_path(@certification), method: :delete, class: 'btn btn-danger', data: { dismiss: :modal } %>
      </div>
    </div>
  </div>
</div>
<!-- End Deletion Modal -->

app/views/certifications/index.html.erb
<% content_for(:title, 'Certifications') %>

<div class="row">
  <div class="col-lg-12">
    <div class="card border-0">
      <div class="card-header bg-dark text-light">
        <div class="row">
          <div class="col-auto mr-auto pt-1">
            Certifications
          </div>
          <% if policy(Certification).create? -%>
              <div class="col-auto">
                <%= link_to new_certification_path, class: 'event-title-btn', 'data-toggle': :tooltip, 'data-placement': :bottom, title: 'Add Certification' do %>
                    <%= fa_icon('plus-square') %>
                <% end %>
              </div>
          <% end -%>
        </div>
      </div>

      <div class="card-body pb-0 pl-0 pr-0 pt-0">
        <table class="table table-sm table-bordered table-responsive mb-0">
          <tbody>
          <tr class="bg-light">
            <% if policy(Certification).update? -%>
              <th></th>
            <% end -%>
            <th>
              <small>Name</small>
            </th>
            <th class="text-center">
              <small>Short Name</small>
            </th>
            <th class="text-center">
              <small>Major</small>
            </th>
            <th class="text-center">
              <small>Display on Roster</small>
            </th>
            <th class="text-center">
              <small>Positions</small>
            </th>
            <th class="text-center">
              <small>Endorsements</small>
            </th>
          </tr>
          <% if @certifications.empty? %>
              <tr>
                <td colspan="8" class="text-center">
                  <small><i>No information available</i></small>
                </td>
              </tr>
          <% end %>

          <% @certifications.order(:name).each do |c| -%>
            <tr>
              <% if policy(Certification).update? -%>
                <td class="text-center">
                  <%= link_to edit_certification_path(c),
                              class: 'badge badge-secondary',
                              'data-toggle': :tooltip,
                              'data-placement': :bottom,
                              title: 'Edit' do %>
                    <%= fa_icon 'pencil' %>
                  <% end %>
                </td>
              <% end -%>
              <td>
                <small><%= c.name %></small>
              </td>
              <td class="text-center">
                <small><%= c.short_name %></small>
              </td>
              <td class="text-center">
                <small><%= c.major? ? fa_icon('check') : nil %></small>
              </td>
              <td class="text-center">
                <small><%= c.show_on_roster? ? fa_icon('check') : nil %></small>
              </td>
              <td class="text-center">
                <small><%= c.positions.count %></small>
              </td>
              <td class="text-center">
                <small><%= c.users.count %></small>
              </td>
            </tr>
            <%#= render 'position', position: p %>
          <% end -%>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

app/views/certifications/new.html.erb
<% content_for(:title, 'New Certification') %>

<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header bg-dark text-light">
        <div class="row">
          <div class="col-auto mr-auto pt-1">
            New Certification
          </div>
        </div>
      </div>

      <div class="card-body pl-0 pr-0">
        <%= render 'form' %>
      </div>

    </div>
  </div>
</div>