config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
      controllers: {
          omniauth_callbacks: 'omniauth_callbacks'
      },
      skip: [:sessions]

  # Manually manage sign out path due to the lack of database authenticatable
  devise_scope :user do
	  post   '/users/auth/2fa' => 'omniauth_callbacks#authenticate_with_two_factor' # Handle 2FA callbacks
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :activity, only: [:index]

  resources :airports

  resources :certifications

  resources :events do
    get 'signup' => 'events/signups#new'

    resources :signups, except: [:new], controller: 'events/signups'
    resources :pilots, only: [:create, :destroy], controller: 'events/pilots'
    resources :positions, except: [:create, :destroy, :new, :show], controller: 'events/positions'
  end

  resources :feedback, except: [:edit, :show]
  resources :groups, except: [:show]
  resources :positions

  resource :profile, only: [:show, :update] do
    resource :gpg_key, only: [:create, :destroy, :show], controller: 'profiles/gpg_key'
	  resource :two_factor_auth, only: [:create, :destroy, :show], controller: 'profiles/two_factor_auths' do
		  resources :u2f, only: [:create, :destroy], controller: 'profiles/two_factor_auths/u2f'
	  end
  end

  resources :roster, as: :users do
	  get    'user_info'   => 'roster#user_info'
	  delete 'disable_2fa' => 'roster#disable_2fa'
	  resources :endorsements, only: [:create, :edit, :new, :update, :destroy]
  end
end

app/models/airport.rb
class Airport < ApplicationRecord
	extend FriendlyId
	friendly_id :icao

	has_one :weather, dependent: :destroy
	has_many :charts, class_name: 'Airport::Chart', dependent: :destroy

	validates :icao,
	          presence: true,
	          allow_blank: false,
	          length: { maximum: 4 },
						uniqueness: { case_sensitive: false }

	validates :elevation, allow_nil: true, numericality: {}
	validates :latitude, 	allow_nil: true, numericality: { greater_than_or_equal_to: -90,  less_than_or_equal_to: 90 }
	validates :longitude, allow_nil: true, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
	validates :name, presence: true, allow_blank: false

	after_create :queue_update

	# Ensure ICAO identifiers are uppercase
	#
	def icao=(ident)
		ident.nil? ? super(ident) : super(ident.upcase)
	end

	# Ensure name is titleized
	#
	def name=(name)
		name.nil? ? super(name) : super(name.titleize)
	end

	private

	# Queue the AirportUpdate job to poll data
	#
	def queue_update
		AirportUpdateJob.perform_later(self)
	end

end

app/models/airport/chart.rb
class Airport::Chart < ApplicationRecord
  belongs_to :airport

  validates :category, presence: true, allow_blank: false
  validates :name,     presence: true, allow_blank: false
  validates :url,      presence: true, allow_blank: false

end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  after_action :verify_authorized

  def index
    @airports = Airport.all.order(:icao)
    authorize @airports
  end

  def create
    authorize Airport, :create?
    @airport = Airport.new

    if @airport.update_attributes(permitted_attributes(@airport))
      redirect_to airports_path, success: 'Airport has been saved'
    else
      flash.now[:alert] = 'Unable to save airport'
      render :new
    end
  end

  def destroy
    authorize Airport, :destroy?
    @airport = policy_scope(Airport).friendly.find(params[:id])

    if @airport.destroy
      redirect_to airports_path, success: 'Airport has been deleted'
    else
      redirect_to airport_path(@airport), alert: 'Unable to delete airport'
    end
  end

  def edit
    @airport = policy_scope(Airport).friendly.find(params[:id])
    authorize @airport
  end

  def new
    @airport = Airport.new
    authorize @airport
  end

  def show
    @airport = policy_scope(Airport).friendly.find(params[:id])
    authorize @airport
  end

  def update
    authorize Airport, :update?
    @airport = policy_scope(Airport).friendly.find(params[:id])

    if @airport.update_attributes(permitted_attributes(@airport))
      flash[:success] = "#{@airport.icao} has been updated"
      redirect_to airports_path
    else
      flash.now[:alert] = 'Unable to update airport'
      render :edit
    end
  end

end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/views/airports/_airport.html.erb
<tr>
  <% if policy(Airport).update? -%>
    <td class="text-center">
      <%= link_to edit_airport_path(airport),
                  class: 'badge badge-secondary',
                  'data-toggle': :tooltip,
                  'data-placement': :bottom,
                  title: 'Edit' do %>
        <%= fa_icon 'pencil' %>
      <% end %>
    </td>
  <% end -%>
  <td class="text-center">
    <small>
      <%= link_to airport.icao, airport_path(airport) %>
    </small>
  </td>
  <td class="text-center">
    <small><%= airport.name %></small>
  </td>
  <td class="text-center">
    <small><%= airport.charts.count %></small>
  </td>
  <td class="text-center <%= airport.weather.rules.downcase unless airport.weather.nil? %>">
    <small class="text-white"><%= airport.weather.rules unless airport.weather.nil? %></small>
  </td>
  <td class="text-center">
    <small><%= airport.weather.wind unless airport.weather.nil? %></small>
  </td>
  <td class="text-center">
    <small><%= '%.2f' % airport.weather.altimeter unless airport.weather.nil? %></small>
  </td>
</tr>

app/views/airports/_charts.html.erb
<% categories = @airport.charts.pluck('category').uniq %>

<ul class="nav nav-tabs" id="airportCharts" role="tablist">
  <% categories.each do |category| -%>
    <% first = (categories.first == category) %>
    <% first ? css      = 'nav-link active' : css = 'nav-link' %>
    <% first ? selected = 'true' : selected = 'false' %>

    <li class="nav-item">
      <%= link_to category, "##{category}",
                  id:               "#{category}-tab",
                  class:            css,
                  'data-toggle':    'tab',
                  role:             'tab',
                  'aria-controls':  category,
                  'aria-selected':  selected %>
    </li>
  <% end -%>
</ul>

<div class="tab-content" id="airportChartsContent">
  <% categories.each do |category| -%>
    <% first = (categories.first == category) %>
    <% first ? css      = 'show active' : css = nil %>

    <div class="tab-pane fade <%= css %>" id="<%= category %>" role="tabpanel" aria-labelledby="<%= category %>-tab">
      <table class="table table-sm table-bordered table-responsive mb-0">
        <tbody>
          <% @airport.charts.where(category: category).order(:name).each do |chart| -%>
            <tr>
              <td>
                <small><%= link_to chart.name, chart.url, target: :blank %></small>
              </td>
            </tr>
          <% end -%>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/airports/_form.html.erb
<div class="container">
  <%= form_for @airport do |f| %>

      <div class="form-group row">
        <%= f.label :icao, 'ICAO', class: 'col-sm-3 col-form-label' %>
        <div class="col-sm-9">
          <% @airport.errors[:icao].present? ? icao_invalid = 'is-invalid' : icao_invalid = nil %>
          <%= f.text_field :icao, class: "form-control #{icao_invalid}", placeholder: 'Example: KIWS', required: true %>
          <% unless icao_invalid.nil? %>
            <div class="invalid-feedback">
              <%= @airport.errors[:icao].join(', ').capitalize %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :name, class: 'col-sm-3 col-form-label' %>
        <div class="col-sm-9">
          <% @airport.errors[:name].present? ? name_invalid = 'is-invalid' : name_invalid = nil %>
          <%= f.text_field :name, class: "form-control #{name_invalid}", placeholder: 'Example: West Houston', required: true %>
          <% unless name_invalid.nil? %>
              <div class="invalid-feedback">
                <%= @airport.errors[:name].join(', ').capitalize %>
              </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-3 col-form-label">Display</div>
        <div class="col-sm-9 form-check form-check-inline">
          <%= f.check_box :show_metar, class: 'form-check-label' %>
          <%= f.label 'Show weather in Airport Conditions panel (if weather is available)', class: 'col-form-label' %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-12 text-center">
          <%= f.submit 'Save Airport', class: 'btn btn-primary' %>
          <%= link_to 'Cancel', airports_path, class: 'btn btn-outline-info' %>
        </div>
      </div>
  <% end %>
</div>

app/views/airports/edit.html.erb
<% content_for(:title, 'Edit Airport') %>

<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header bg-dark text-light">
        <div class="row">
          <div class="col-auto mr-auto pt-1">
            Edit Airport
          </div>
          <% if policy(@airport).destroy? -%>
              <div class="col-auto">
                <%= link_to '#', class: 'btn btn-sm btn-outline-danger', title: 'Delete Airport', data: {toggle: :modal, target: '#airportDeleteModal'} do %>
                    <%= fa_icon('trash') %> Delete
                <% end %>
              </div>
          <% end -%>
        </div>
      </div>

      <div class="card-body pl-0 pr-0">
        <%= render 'form' %>
      </div>

    </div>
  </div>
</div>

<!-- Deletion Modal -->
<div class="modal fade" id="airportDeleteModal" tabindex="-1" role="dialog" aria-labelledby="airportDeleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="airportDeleteModalLabel">
          <%= fa_icon 'exclamation-triangle', class: 'text-danger' %> Delete Airport
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>
          Are you sure you want to delete <%= @airport.name %> (<%= @airport.icao %>)?
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= link_to 'Delete', airport_path(@airport), method: :delete, class: 'btn btn-danger', data: { dismiss: :modal } %>
      </div>
    </div>
  </div>
</div>
<!-- End Deletion Modal -->

app/views/airports/index.html.erb
<% content_for(:title, 'Airports') %>

<div class="row">
  <div class="col-lg-12">
    <div class="card border-0">
      <div class="card-header bg-dark text-light">
        <div class="row">
          <div class="col-auto mr-auto pt-1">
            Airport Information
          </div>
          <% if policy(Airport).create? -%>
              <div class="col-auto">
                <%= link_to new_airport_path, class: 'event-title-btn', 'data-toggle': :tooltip, 'data-placement': :bottom, title: 'Add Airport' do %>
                  <%= fa_icon('plus-square') %>
                <% end %>
              </div>
          <% end -%>
        </div>
      </div>

      <div class="card-body pb-0 pl-0 pr-0 pt-0">
        <table class="table table-sm table-bordered table-responsive mb-0">
          <tbody>
          <tr class="bg-light">
            <% if policy(Airport).update? -%>
              <th></th>
            <% end -%>
            <th class="text-center">
              <small>ICAO</small>
            </th>
            <th class="text-center">
              <small>Name</small>
            </th>
            <th class="text-center">
              <small>Charts</small>
            </th>
            <th class="text-center">
              <small>Rules</small>
            </th>
            <th class="text-center">
              <small>Wind</small>
            </th>
            <th class="text-center">
              <small>Altimeter</small>
            </th>
          </tr>
          <% if @airports.empty? %>
            <tr>
              <td colspan="7" class="text-center">
                <small><i>No information available</i></small>
              </td>
            </tr>
          <% end %>

          <% @airports.each do |a| -%>
            <%= render 'airport', airport: a %>
          <% end -%>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

app/views/airports/new.html.erb
<% content_for(:title, 'New Airport') %>

<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header bg-dark text-light">
        New Airport
      </div>

      <div class="card-body pl-0 pr-0">
        <%= render 'form' %>
      </div>

    </div>
  </div>
</div>

app/views/airports/show.html.erb
<% content_for(:title, "#{@airport.name} (#{@airport.icao})") %>

<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header bg-dark text-light">
        <div class="row">
          <div class="col-auto mr-auto pt-1">
            <%= @airport.name %> (<%= @airport.icao %>)
          </div>
          <div class="col-auto">
            <% if policy(@airport).edit? %>
                <%= link_to 'Edit', edit_airport_path(@airport), class: 'btn btn-sm btn-outline-warning', title: 'Edit Airport' %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="card-body">
        <div class="row">
          <div class="col-md-8">
            <div class="row">
              <div class="col-sm-12">
                <strong><%= @airport.name %></strong>
              </div>
            </div>
            <% if @airport.latitude && @airport.longitude -%>
              <div class="row">
                <div class="col-sm-12">
                  <strong>Coordinates:</strong>
                  <%= @airport.latitude %>, <%= @airport.longitude %>
                </div>
              </div>
            <% end -%>
            <% if @airport.elevation -%>
              <div class="row">
                <div class="col-sm-12">
                  <strong>Elevation:</strong>
                  <%= @airport.elevation %>ft MSL
                </div>
              </div>
            <% end -%>
            <% if @airport.weather -%>
              <div class="row mt-2">
                <div class="col-sm-2 text-center">
                  <h4>
                    <span class="badge badge-primary <%= @airport.weather.rules.downcase %>">
                      <%= @airport.weather.rules %>
                    </span>
                  </h4>
                </div>
                <div class="col-sm-10 text-muted">
                  <%= @airport.weather.metar %>
                </div>
              </div>
            <% end -%>
          </div>

          <div class="col-md-4">
            <span class="float-right">
              <h1 class="text-muted"><%= @airport.icao %></h1>
            </span>
          </div>
        </div>

        <div class="top-buffer"></div>

        <%= render 'charts' unless @airport.charts.empty? %>
      </div>

    </div>
  </div>
</div>