config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
      controllers: {
          omniauth_callbacks: 'omniauth_callbacks'
      },
      skip: [:sessions]

  # Manually manage sign out path due to the lack of database authenticatable
  devise_scope :user do
	  post   '/users/auth/2fa' => 'omniauth_callbacks#authenticate_with_two_factor' # Handle 2FA callbacks
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :activity, only: [:index]

  resources :airports

  resources :certifications

  resources :events do
    get 'signup' => 'events/signups#new'

    resources :signups, except: [:new], controller: 'events/signups'
    resources :pilots, only: [:create, :destroy], controller: 'events/pilots'
    resources :positions, except: [:create, :destroy, :new, :show], controller: 'events/positions'
  end

  resources :feedback, except: [:edit, :show]
  resources :groups, except: [:show]
  resources :positions

  resource :profile, only: [:show, :update] do
    resource :gpg_key, only: [:create, :destroy, :show], controller: 'profiles/gpg_key'
	  resource :two_factor_auth, only: [:create, :destroy, :show], controller: 'profiles/two_factor_auths' do
		  resources :u2f, only: [:create, :destroy], controller: 'profiles/two_factor_auths/u2f'
	  end
  end

  resources :roster, as: :users do
	  get    'user_info'   => 'roster#user_info'
	  delete 'disable_2fa' => 'roster#disable_2fa'
	  resources :endorsements, only: [:create, :edit, :new, :update, :destroy]
  end
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  paginates_per 10

  validates :anonymous,     inclusion: { in: [ true, false ] }
  validates :cid,           presence: true, allow_blank: false, unless: :anonymous?
  validates :name,          presence: true, allow_blank: false, unless: :anonymous?
  validates :email,         presence: true, allow_blank: false, unless: :anonymous?
  validates :callsign,      presence: true, allow_blank: false, unless: :anonymous?
  validates :controller,    presence: true, allow_blank: false
  validates :position,      presence: true, allow_blank: false
  validates :service_level, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 5 }
  validates :fly_again,     inclusion: { in: [ true, false ] }
  validates :comments,      presence: true, allow_blank: false
  validates :published,     inclusion: { in: [ true, false ] }

  # Forces the callsign to upper case
  #
  def callsign=(callsign)
    callsign.nil? ? super(callsign) : super(callsign.upcase)
  end

end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
  before_action :authenticate_user!, except: [:index, :new, :show]
  after_action :verify_authorized, except: :new

  def index
    @feedback = policy_scope(Feedback).page params[:page]
    authorize @feedback
  end

  def create
    authorize Feedback, :create?
    @feedback = Feedback.new

    # Do not set the following parameters if feedback is send anonymously
    unless params['feedback']['anonymous'] == '1'
      @feedback.cid   = current_user.cid
      @feedback.name  = current_user.name_full
      @feedback.email = current_user.email
    end

    if @feedback.update_attributes(permitted_attributes(@feedback))
      flash[:success] = t('feedback.alerts.create.success') unless t('feedback.alerts.create.success').blank?
      redirect_to feedback_index_path
    else
      flash.now[:alert] = t('feedback.alerts.create.errors')
      render :new
    end
  end

  def destroy
    authorize Feedback, :destroy?
    @feedback = policy_scope(Feedback).find(params[:id])

    if @feedback.destroy
      redirect_to feedback_index_path, success: t('feedback.alerts.destroy.success')
    else
      redirect_to feedback_index_path, alert: t('feedback.alerts.destroy.errors')
    end
  end

  def new
    if user_signed_in?
      @feedback = Feedback.new
      authorize @feedback
    else
      redirect_to user_vatsim_omniauth_authorize_path
    end
  end

  def update
    authorize Feedback, :update?
    @feedback = policy_scope(Feedback).find(params[:id])

    if @feedback.update_attributes(permitted_attributes(@feedback))
      flash[:success] = t('feedback.alerts.update.success')
      redirect_to feedback_index_path
    else
      flash.now[:alert] = t('feedback.alerts.update.errors')
      render :edit
    end
  end

end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/views/feedback/_controls.html.erb
<% if policy(feedback).update? || policy(feedback).destroy? %>
    <div class="row alert-secondary ml-2 mr-2 pt-1 pb-1 rounded">
      <div class="col-auto mr-auto">
        <% if policy(feedback).edit? %>
          <% if feedback.published? %>
            <%= link_to feedback_path(feedback, feedback: {published: false}), method: :put, class: 'btn btn-sm btn-success ml-2', title: 'Published' do %>
              <%= fa_icon 'eye' %>
            <% end %>
          <% else %>
            <%= link_to feedback_path(feedback, feedback: {published: true}), method: :put, class: 'btn btn-sm btn-outline-info ml-2', title: 'Unpublished' do %>
              <%= fa_icon 'eye-slash' %>
            <% end %>
          <% end %>
        <% end %>

        <% if policy(feedback).destroy? %>
          <%= link_to feedback_path(feedback), method: :delete, data: { confirm: 'Are you sure? '}, class: 'btn btn-sm btn-danger ml-2', title: 'Delete' do %>
            <%= fa_icon 'trash' %>
          <% end %>
        <% end %>
      </div>

      <div class="col-auto">
        <% unless feedback.anonymous? %>
          <span class="small mt-1">
            <%= feedback.name %> (<%= mail_to feedback.email, nil, class: 'alert-link' %>)
          </span>
        <% end %>

        <% unless feedback.fly_again? %>
          <span class="badge badge-danger">Would not fly again</span>
        <% end %>
      </div>
    </div>
<% end %>

app/views/feedback/_form.html.erb
<div class="container">
  <%= form_for(:feedback, url: feedback_index_path) do |f| %>
    <div class="form-group row">
      <label for="submitter" class="col-sm-3 col-form-label">Name</label>
      <div class="col-sm-9">
        <input type="name" class="form-control" id="feedbackName" placeholder="<%= current_user.name_full %> (<%= current_user.cid %>)" readonly>
      </div>
    </div>

    <div class="form-group row">
      <label for="email" class="col-sm-3 col-form-label">Email</label>
      <div class="col-sm-9">
        <input type="email" class="form-control" id="feedbackEmail" placeholder="<%= current_user.email %>" readonly>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-3 col-form-label">Privacy</div>
      <div class="col-sm-9 form-check form-check-inline">
        <%= f.check_box :anonymous, class: 'form-check-label', id: 'feedbackAnonymous' %>
        <%= f.label 'Post feedback anonymously', class: 'col-form-label' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :callsign, class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-9">
        <% @feedback.errors[:callsign].present? ? callsign_invalid = 'is-invalid' : callsign_invalid = nil %>
        <%= f.text_field :callsign, class: "form-control text-uppercase #{callsign_invalid}", id: 'feedbackCallsign' %>
        <% unless callsign_invalid.nil? %>
          <div class="invalid-feedback">
            Please provide the callsign you were using.
          </div>
        <% end %>
      </div>
    </div>

    <% controllers = User.all_controllers.order(:name_first).collect{|a| [ a.name_full, a.name_full ]} %>
    <% controllers.unshift ['Unknown (Not specified)', 'Not specified'] %>

    <div class="form-group row">
      <%= f.label :controller, class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-9">
        <%= f.select :controller, controllers, {}, class: 'form-control' %>
      </div>
    </div>

    <% positions = Position.all.order(:callsign).collect{|p| ["#{p.callsign} (#{'%.3f' % p.frequency})", p.callsign]} %>
    <% positions.unshift ['Unknown (Not specified)', 'Not specified'] %>

    <div class="form-group row">
      <%= f.label :position, class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-9">
        <%= f.select :position, positions, {}, class: 'form-control' %>
      </div>
    </div>

    <% service_levels = [['Excellent', 5], ['Good', 4], ['Fair', 3], ['Poor', 2], ['Unsatisfactory', 1]] %>

    <div class="form-group row">
      <%= f.label :service_level, 'Level of service', class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-9">
        <%= f.select :service_level, service_levels, {}, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :fly_again, 'Would you fly again?', class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-9">
        <%= f.select :fly_again, [['Yes', true], ['No', false]], {}, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :comments, class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-9">
        <% @feedback.errors[:comments].present? ? comments_invalid = 'is-invalid' : comments_invalid = nil %>
        <%= f.text_area :comments, class: "form-control #{comments_invalid}" %>
        <% unless comments_invalid.nil? %>
            <div class="invalid-feedback">
              Please provide your comments.
            </div>
        <% end %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-12 text-center">
        <%= f.submit 'Send Feedback', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/feedback/index.html.erb
<% content_for(:title, 'Feedback') %>

<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header bg-dark text-light">
        <div class="row">
          <div class="col-auto mr-auto pt-1">Feedback Archive</div>
          <div class="col-auto">
            <% if policy(Feedback).create? || current_user.nil? -%>
              <%= link_to 'Leave Feedback', new_feedback_path, class: 'btn btn-sm btn-outline-info' %>
            <% end -%>
          </div>
        </div>
      </div>
      <div class="card-body pl-0 pr-0">
        <% if @feedback.empty? %>
          <p class="text-center font-italic top-buffer">There is currently no feedback</p>
        <% end %>
        <% @feedback.each do |f| %>
        <div class="ml-2 mr-2 pl-2 pr-2 pb-2 pt-2">
          <div class="row">
            <div class="col-md-3 col-auto mr-auto">
              <h5><%= f.position %></h5>
            </div>
            <div class="col-auto">
              <%= f.created_at.strftime('%B %d, %Y') %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-7 col-auto mr-auto">
              <small><%= f.controller %></small>
            </div>
            <div class="col-auto">
              <% f.service_level.times do %>&#9733;<% end %>
            </div>
          </div>
          <div class="row top-buffer">
            <div class="col-md-12">
              <blockquote class="blockquote pl-4">
                <p class="mb-0">"<%= f.comments %>"</p>
                <footer class="blockquote-footer">
                  <% if f.anonymous? %>
                    Anonymous
                  <% else %>
                    <%= f.name %>
                    (<%= link_to f.cid, "#{Settings.stats_url}#{f.cid}" %>)
                    operating as <%= f.callsign %>
                  <% end %>
                </footer>
              </blockquote>
            </div>
          </div>

          <%= render 'controls', feedback: f %>
        </div>
        <div class="row top-buffer"></div>
        <% end %>

        <div class="row">
          <div class="d-flex mx-auto">
            <%= paginate @feedback, theme: 'twitter-bootstrap-4', pagination_class: 'pagination-sm' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/feedback/new.html.erb
<% content_for(:title, 'Leave Feedback') %>

<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header bg-dark text-light">
        Leave Feedback
      </div>

      <div class="card-body pl-0 pr-0">
        <%= render 'form' %>
      </div>

    </div>
  </div>
</div>